### ISSUE TITLE
ヘモシアニンがヘモグロビンになった理由について

### ISSUE THREAD

**Issue by kwaka1208** [kwaka1208/KidsQuestion#1]
友人の息子さんが「はたらく細胞」というアニメにはまって、以下のような疑問を持っているそうです。
```
「赤いから赤血球なら、イカは青の血だから青血球なのか？」と言うので調べてみると、
青の血は血球ではなくヘモシアニンという色素がそのまま血液中を流れているそうで。
「なんで血球になったんやろね。進化？進化なら血球の方がいいって事やな？血球の方がなんでいいの？」。
なぜ、ヘモシアニンがヘモグロビンになったのも何でなんかな。銅より鉄の方が酸素運ぶのに効率いいのかな。
```
この疑問に答えられる方、もしくは関連する情報持っている方（完璧でなくてもいいです）コメントいただけれる方、コメントをいただくか kwaka1208@gmail.com までご連絡ください。

**Comment by kamataryo** [comment]
私は答えを持ってないので雑談的になってしまうんですが、「生物が進化の中でなぜそういう形質を獲得したのか」（適応の意義）をズバっと答えるのは難しいんですよね。答えはないと思っていて、ですので、関係しそうな生物の生理・生態のトピックを列挙するのに留めます。

- ヘモグロビンやヘモシアニンなどの酸素結合タンパク質の化学特性
    - 酸素分圧、二酸化炭素分圧、pH に影響される。「酸素解離曲線」は高校の化学で扱われているのでわかりやすいです
- 赤血球の特徴
    - 酸素運搬に特化している（脱核とか）
    - 多くの脊椎動物にあって無脊椎動物にない特徴
- イカ・タコなどの海産無脊椎動物の恒常性（ホメオスタシス）
    - 浸透圧順応型 (塩分を自力で調節しない) https://www.press.tokai.ac.jp/webtokai/uminiikiru7.pdf
    - 変温動物
- 海産無脊椎動物はベントス（底生性）なものが多い、脊椎動物はネクトン（浮遊性）

以下のようなことは言ってもいいと思います。
「無脊椎動物と比べて、脊椎動物は高い運動能力を活かした生態を持つものが多く、ヘモグロビンや赤血球のような形質の獲得は、これに大きく寄与しているようだ。」

進化に関しては、以下のようにストーリーを適当に作ることはできますが、裏を取るのは多分無理でしょう😅
「無脊椎動物から脊椎動物への大進化の中で、海底から水柱全体に進出するために代謝と活動性を獲得することが必要で、酸素運搬効率の良いヘモグロビンを含む赤血球を利用する形質を獲得した。一方で、無脊椎動物は、既存のニッチを維持するためには、効率が劣るヘモシアニンで十分だったり、あるいはむしろヘモシアニンの方が有利だったりしたため（特異な環境下での酸素運搬効率がヘモグロビンより良い、みたいなことはありうる）、コストをかけてヘモグロビンを獲得する必要はなかった。」

**Comment by kwaka1208** [comment]
ありがとうございます。完璧な答えじゃなくていいと思うんです、それをきっかけに子供達がもっと深く追ってみたいと思えるのがいいなって思ってます。

**Comment by kwaka1208** [comment]
ただ、これを子供にわかりやすく伝えるのが難しい...。
